language: node_js
node_js:
- 8.0
before_install:
- openssl aes-256-cbc -K $encrypted_3a594aa52544_key -iv $encrypted_3a594aa52544_iv -in deploy_key.enc -out deploy_key -d
before_script:
script:
- gulp
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config user.name "Automatic Publish"
- git config user.email "ci@travis.org"
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; git subtree push --prefix docs origin gh-pages; fi;
